services:
  rabbit-server:
    image: rabbitmq:3-management
    container_name: rabbit-server
    hostname: rabbit-host
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: unless-stopped
    networks:
      - app_network
  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_DB: postgres_db
    ports:
      - "5430:5432"
    restart: always
    networks:
      - app_network
  creator:
    build:
      context: .
      dockerfile: creator/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - rabbit-server
    volumes:
      - ./creator:/creator_app
    command: ["sh", "-c", "sleep 5; python main.py"]
    networks:
      - app_network
  worker:
    build:
      context: .
      dockerfile: worker/Dockerfile
    depends_on:
      - rabbit-server
      - postgres
    volumes:
      - ./worker:/worker_app
    command: ["sh", "-c", "sleep 5; faststream run main:app"]
    networks:
      - app_network

networks:
  app_network:
    driver: bridge